import type { Sport } from "../types";

export interface DrillCategory {
  id: string;
  name: string;
  drills: string[];
}

export const WRESTLING_DRILLS: DrillCategory[] = [
  {
    id: "stance-motion",
    name: "Stance & Motion",
    drills: [
      "Stance & Motion",
      "Circle Drill",
      "Hand Fighting",
      "Pummeling",
      "Tie-Up Practice",
      "Penetration Step",
    ],
  },
  {
    id: "takedowns",
    name: "Takedowns",
    drills: [
      "Single Leg",
      "Double Leg",
      "High Crotch",
      "Ankle Pick",
      "Snap Down",
      "Duck Under",
      "Fireman's Carry",
      "Arm Drag",
      "Head & Arm Throw",
      "Foot Sweep",
    ],
  },
  {
    id: "defense",
    name: "Defense",
    drills: [
      "Sprawl Drill",
      "Solo Sprawl",
      "Shot Defense (Whizzer)",
      "Front Headlock",
      "Down Block",
      "Reshot / Counter",
    ],
  },
  {
    id: "top",
    name: "Top Position",
    drills: [
      "Tight Waist & Ankle",
      "Spiral Ride",
      "Half Nelson",
      "Chicken Wing",
      "Cradle",
      "Bar Arm",
      "Turk",
      "Mat Return",
    ],
  },
  {
    id: "bottom",
    name: "Bottom Position",
    drills: [
      "Stand-Up",
      "Sit-Out Turn-In",
      "Sit-Out Turn-Out",
      "Switch",
      "Granby Roll",
      "Hip Heist",
      "Peterson Roll",
    ],
  },
  {
    id: "conditioning",
    name: "Conditioning & Body",
    drills: [
      "Bridging / Neck",
      "Partner Carries",
      "Spin Drill",
      "Airplane Drill",
      "Shots for Time",
      "Sprints",
      "Buddy Lifts",
    ],
  },
  {
    id: "freestyle",
    name: "Freestyle",
    drills: [
      "Leg Lace",
      "Gut Wrench",
      "Reverse (Dagestani) Gut",
      "Trap-Arm Gut",
      "Cement Mixer",
      "Far-Ankle Lift",
      "High-Crotch Lift",
      "Body Lock Throw",
      "Arm Spin",
      "Lateral Drop",
      "Fireman's from Underhook",
      "Ankle Pick (Freestyle)",
      "Push-Out Wrestling",
      "Par Terre Defense",
    ],
  },
  {
    id: "greco",
    name: "Greco-Roman",
    drills: [
      "Pummeling for Underhooks",
      "Double Underhook Lock",
      "Bodylock Throw",
      "Arm Throw",
      "Headlock Throw",
      "Flying Mare",
      "Souplesse / Suplex",
      "Lateral Drop (Greco)",
      "Front Headlock Spin",
      "Arm Drag to Back",
      "Reverse Lift (Par Terre)",
      "Gut Wrench (Greco)",
      "Arm Bar Turn",
      "Par Terre Defense (Greco)",
    ],
  },
];

export const VOLLEYBALL_DRILLS: DrillCategory[] = [
  // --- Skill Fundamentals ---
  {
    id: "ball-control",
    name: "Ball Control",
    drills: [
      "Pepper",
      "Partner Pepper with Movement",
      "Wall Passing",
      "Wall Setting Rapid-Fire",
      "Solo Ball Handling",
      "Bump-Set-Bump",
      "Around the World",
      "Solo Passing Triangle",
      "Toss-Bounce-Catch (low base)",
    ],
  },
  {
    id: "serving",
    name: "Serving",
    drills: [
      "Underhand Serve",
      "Standing Float Serve",
      "Jump Float Serve",
      "Jump Topspin Serve",
      "Zone Targeting (1-6)",
      "Short Serves",
      "Deep Serves",
      "Line Serves",
      "Cross-Court Serves",
      "Seam Serves",
      "Tough Serve Challenge",
      "Serve in a Row (consistency)",
    ],
  },
  {
    id: "passing",
    name: "Passing & Serve Receive",
    drills: [
      "Forearm Pass Technique",
      "Platform Drill (coach toss)",
      "Butterfly Drill",
      "Shuffle Pass",
      "3-Player Weave",
      "Target Passing",
      "Short / Deep Pass Reaction",
      "Over-the-Shoulder Pass",
      "J-Stroke Pass",
      "Serve Receive (2-passer)",
      "Serve Receive (3-passer)",
      "Pass & Switch",
    ],
  },
  {
    id: "setting-fund",
    name: "Setting Fundamentals",
    drills: [
      "Setting Technique",
      "Triangle Window Hands",
      "Seated Setting",
      "Wall Setting",
      "Setting to Target (4 / 2)",
      "Front Set",
      "Back Set",
      "High Outside (4-ball)",
      "Short Quick (1-ball)",
      "Back-Row D (back-row set)",
    ],
  },
  {
    id: "hitting-fund",
    name: "Hitting Fundamentals",
    drills: [
      "3-Step Approach",
      "4-Step Approach (R-L-R-L)",
      "Approach Footwork (no ball)",
      "Wall Hitting",
      "Arm Swing Mechanics",
      "Hip Rotation Drill",
      "Hit vs. Tip Decision",
      "Line Shot",
      "Cross-Court Shot",
      "Roll Shot",
      "Deep Corner Hit",
      "Hitting Lines (coach toss)",
      "Pass-Set-Hit",
    ],
  },
  {
    id: "blocking-defense",
    name: "Blocking & Defense",
    drills: [
      "Block Footwork (3-step crossover)",
      "Close the Block (outside)",
      "Seal the Net",
      "Hands Penetration over Net",
      "Solo Block Jumps",
      "Block & Transition",
      "Pancake / Sprawl Dig",
      "Wall Digs (rapid fire)",
      "Reading the Hitter",
      "Roll Shot Defense",
      "Tip Coverage",
    ],
  },

  // --- Position-Specific ---
  {
    id: "pos-setter",
    name: "Setter Position",
    drills: [
      "Seated Target Setting",
      "Wall Rapid-Fire Setting",
      "Left-Right Footwork to Target",
      "Setter Release from Base",
      "Setter Release from Right Back",
      "Jump Setting Progression",
      "Front-Only Set Sequence",
      "Back-Only Set Sequence",
      "Quick 1-Ball Timing",
      "Setter Transition Back to Base",
      "Deep Pass Adjustment",
      "Setter Dump / Attack",
      "Read & Release",
      "Running Slide Timing",
      "Emergency High Ball",
    ],
  },
  {
    id: "pos-libero",
    name: "Libero / Defensive Specialist",
    drills: [
      "Platform Development (coach toss)",
      "Wall Digs (rapid fire)",
      "Shuffle-and-Dig",
      "Cross-Court Dig Footwork",
      "Reading the Hitter",
      "Pancake Recovery",
      "J-Stroke Pass",
      "Serve Receive Movement",
      "Deep Serve Reaction",
      "Short Serve Sprint",
      "Roll Shot Defense",
      "Free Ball Pass to Target",
      "Emergency Dig",
      "Run-Through Pass",
      "Libero Transition",
      "Back Row Communication",
    ],
  },
  {
    id: "pos-middle",
    name: "Middle Blocker",
    drills: [
      "3-Step Crossover Left",
      "3-Step Crossover Right",
      "Mirror the Setter",
      "Close the Block to Pin",
      "Seal the Net",
      "Penetrate Hands over Net",
      "Quick 1-Ball Attack Timing",
      "Slide Footwork",
      "Slide Attack",
      "Middle-to-Pin Footwork",
      "Middle Transition & Approach",
      "Block Release to Approach",
      "Commit Block Drill",
      "Read Block Drill",
      "Double / Triple Block",
      "10-in-a-Row Jump Endurance",
    ],
  },
  {
    id: "pos-outside",
    name: "Outside Hitter",
    drills: [
      "3-Step Approach",
      "4-Step Approach (R-L-R-L)",
      "Arm Swing Mechanics",
      "Hip Rotation Drill",
      "High Ball Outside (4-set)",
      "Go / Hut Tempo Sets",
      "Line vs. Cross Shot",
      "Tip Behind Block",
      "Roll Shot to Zone 6",
      "Pass & Hit (P&H)",
      "Serve Receive to Attack",
      "Swing Under Block",
      "Deep Corner Hit",
      "Line Block Adjustment",
      "Hitting Lines with Sprints",
    ],
  },
  {
    id: "pos-opposite",
    name: "Opposite / Right Side",
    drills: [
      "Right-Side Approach",
      "Back-Row D Attack",
      "Right-Side Line Hit",
      "Right-Side Cross Hit",
      "Block Against Outside Hitter",
      "Emergency Setting",
      "Right-Side Tip Placement",
      "Shoot Set (31 to right)",
      "Campfire Roll Shot",
      "Right-Side Transition",
      "Hit Over Middle Block",
      "Bic Back-Row Attack",
    ],
  },

  // --- Team & Game ---
  {
    id: "team-game",
    name: "Team & Game",
    drills: [
      "Queen of the Court",
      "6-on-6 Scrimmage",
      "3-Ball Game",
      "Wash Drill",
      "Serve & Pass Competition",
      "Serve-Receive-Attack",
      "Free Ball Transition",
      "Scramble Defense",
      "Down Ball Attack",
      "Point-Game Scoring",
    ],
  },
];

export function drillsForSport(sport: Sport): DrillCategory[] {
  return sport === "wrestling" ? WRESTLING_DRILLS : VOLLEYBALL_DRILLS;
}
